on:
  # push:
  workflow_dispatch:
    inputs:
      depth:


jobs:

  squash-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/gi1-ac2io3s@squash-repo
        with:
          depth: ${{ inputs.depth }}

          auto: true
          token: ${{ secrets.token }}
