on:
#  push:
  workflow_dispatch:


jobs:

  gdrive-reset:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/ac1io2s@checkout-branch
        with:
          token: ${{ secrets.token }}
          auto: true


      - uses: fu1ny2t-3es/go1gl2-dr3ve-4pl5ad-6it-7ct8on@erase-drive
        with:
          credentials: ${{ secrets.gdrive_key }}
          folderId: ${{ secrets.gdrive_folder }}
